spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
          # search-locations: "classpath:/config"
        git:
          uri: "https://github.com/toharifqi/xbank-config.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

server:
  port: 8071

encrypt:
  key: "F39777D7A4F16A7264895B461581D"
